# Generated by Django 3.2.4 on 2021-11-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carditem',
            old_name='product_quantitiy',
            new_name='product_quantity',
        ),
    ]
